name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # ya jo tumhari default branch hai

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd jitendra-portfolio
          npm install

      - name: Build project
        run: |
          cd jitendra-portfolio
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jitendra-portfolio/dist
